### PR TITLE
Initial mapping for ABNT2 keyboards

### PR DESCRIPTION
**Pull request by juracy**
My mapping for ABNT2 keyboards (they are wide used in Brazil)

### CODE REVIEW

**Comment by juracy** [comment]
I think that problem is similar to this:
https://code.google.com/p/chromium/issues/detail?id=432908

**Comment by luisrudge** [comment]
please merge this. this caused too much pain here: https://github.com/OmniSharp/omnisharp-atom/issues/340

**Comment by juracy** [comment]
Thanks, but it solves one problem and raise another... :(

I'm thinking about don't remap 191 and 220 keycodes ... and forget keybinds on them (or remapping keybinds instead) ! :(

**Comment by luisrudge** [comment]
To be fair, all I had to do to fix all my issues was this:

``` json
{
    "81": {
        "alted": 47
    },
    "220": {
        "shifted": 125
    },
    "221": {
        "shifted": 123
    }
}
```

**Comment by juracy** [comment]
I've tested it ! But for example, my normal key (without keybindins) for pipe "|" was changed for closing brackets "}"

My keycode 220 has two shifted keypress: "|" and "}"

:(

**Comment by luisrudge** [comment]
Yeah. True. That fucked up my | too :( Damn

**Comment by juracy** [comment]
The best solution I have so far is not mapping them (those conflicted keycodes: 191 and 220), but in this case I lost some keybindings ! :'(

**Comment by andischerer** [comment]
I've run into the same issue on #12 and #19.
Unfortunately my hands on that are tied and this has to be fixed in chromium/blink engine. 

@juracy is there any work in progress on that or can i merge it in ?

**Comment by juracy** [comment]
@andischerer  I've just removed duplicated keycodes (191 and 220). You can merge it now !

**Comment by andischerer** [comment]
New version is published. Thanks for your help.

**Pull request merged**
