### PR TITLE
Support for en_GB

### PR DESCRIPTION
**Pull request by bookercodes**
Implementation of #101.

Please let me know if there's anything more I can do for this pull request. Thanks :smile:

### CODE REVIEW

**Comment by bluekeys** [comment]
@alexbooker This works for me.Thanks for pointing it out to me.

**Comment by bookercodes** [comment]
@bluekeys You're welcome.

**Comment by sandman21dan** [comment]
Works for me as well!

**Comment by bookercodes** [comment]
@sandman21dan Awesomeee :smile:

**Comment by andischerer** [comment]
Thanks for your work :+1: => merged

**Comment by sandman21dan** [comment]
Brilliant!

**Pull request merged**
