### PR TITLE
Fixed pl_PL layout

### PR DESCRIPTION
**Pull request by macocha**
pl_PL - polish programmers layout.

### CODE REVIEW

**Comment by macocha** [comment]
Just so it's also here (comment from #32):
#33 is not correct implementation of polish programmers layout.
It's strange mix between two layouts used in Poland:
1. http://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/KB_Polish_QWERTZ_PN87_commons.svg/450px-KB_Polish_QWERTZ_PN87_commons.svg.png
2. http://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Polish_programmer%27s_layout.PNG/452px-Polish_programmer%27s_layout.PNG

Layout 1. was really used only in typewriters and never got used a lot in a computer keyboards. Using this layout we can't really enter brackets into a code. I can't think about anyone who would use this layout today and especially not in a code editor.

**Comment by andischerer** [comment]
Thanks for your help. 
Sorry for your work on the 2nd pr.

**Comment by macocha** [comment]
Thanks for the plugin. It really is a godsend for a web development where you have to fill content in your language.

**Comment by andischerer** [comment]
Nice to hear, thanks ;)

**Pull request merged**
