### PR TITLE
Add Belgian French keymap (fr_BE)

### PR DESCRIPTION
**Pull request by filoozom**
Not sure if it's complete, but I'll update it if I find keys that don't work.

### CODE REVIEW

**Comment by andischerer** [comment]
Thanks.
I'll wait for the merge till your testing is done.

**Comment by filoozom** [comment]
Could there be a bug in the `generate-keybindings.html` tool?
I get:

``` json
{
    "48": {
        "unshifted": 224
    },
    "49": {
        "unshifted": 38
    },
    "50": {
        "unshifted": 233
    },
    "51": {
        "unshifted": 34
    },
    "52": {
        "unshifted": 39
    },
    "53": {
        "unshifted": 40
    },
    "54": {
        "unshifted": 167
    },
    "55": {
        "unshifted": 232
    },
    "56": {
        "unshifted": 33
    },
    "57": {
        "unshifted": 231
    }
}
```

on the number row, but it's wrong. None of these keys should have another value when unshifted.
On the fr_BE keyboard, you need to press shift + 0-1 to get a number. By default you get one of "&é"'(§è!çà" (in that order).

**Comment by andischerer** [comment]
Looks right to me. 

e.g when you press the `1` Key(unshifted) on your keyboard, the keydown event resolves with char `1` (49), which is wrong. What you want is the char `&` (38) which keypress resolves correctly.
So a translation from 49 => 38 unshifted is needed.

Activate your generated keymap in atom and check which key gets printed in the keybinding-resolver (`ctrl+.`).

**Comment by andischerer** [comment]
I've generated a keymap for `fr_BE` on the fly (untested). Maybe this bindings work for you.

``` json
{
    "48": {
        "unshifted": 224,
        "alted": 125
    },
    "49": {
        "unshifted": 38,
        "alted": 124
    },
    "50": {
        "unshifted": 233,
        "alted": 64
    },
    "51": {
        "unshifted": 34,
        "alted": 35
    },
    "52": {
        "unshifted": 39,
        "alted": 123
    },
    "53": {
        "unshifted": 40,
        "alted": 91
    },
    "54": {
        "unshifted": 167,
        "alted": 94
    },
    "55": {
        "unshifted": 232
    },
    "56": {
        "unshifted": 33
    },
    "57": {
        "unshifted": 231,
        "alted": 123
    },
    "69": {
        "alted": 8364
    },
    "186": {
        "unshifted": 36,
        "shifted": 42,
        "alted": 93
    },
    "187": {
        "unshifted": 61,
        "shifted": 43,
        "alted": 126
    },
    "188": {
        "unshifted": 44,
        "shifted": 63
    },
    "189": {
        "unshifted": 45,
        "shifted": 95
    },
    "190": {
        "unshifted": 59,
        "shifted": 46
    },
    "191": {
        "unshifted": 58,
        "shifted": 47
    },
    "192": {
        "unshifted": 249,
        "shifted": 37,
        "alted": 180
    },
    "219": {
        "unshifted": 41,
        "shifted": 176
    },
    "220": {
        "unshifted": 181,
        "shifted": 163,
        "alted": 96
    },
    "221": {
        "unshifted": 94,
        "shifted": 168,
        "alted": 91
    },
    "222": {
        "unshifted": 178,
        "shifted": 179
    },
    "226": {
        "unshifted": 60,
        "shifted": 62,
        "alted": 92
    }
}
```

**Comment by filoozom** [comment]
I tried that one, and I have the same problem with the number row.
Unshifted 1 = &, which is right, but shifted 1 = & too, which is wrong.

But I'm probably missing something. The keys work right in the Settings tab but not when editing a file... ?

**Comment by andischerer** [comment]
Ah OK. Tomorrow i'm looking for this. I'm currently not on my dev-mashine.

**Comment by andischerer** [comment]
Could you test the following bindings:

``` json
{
    "48": {
        "unshifted": 224,
        "shifted": 48,
        "alted": 125
    },
    "49": {
        "unshifted": 38,
        "shifted": 49,
        "alted": 124
    },
    "50": {
        "unshifted": 233,
        "shifted": 50,
        "alted": 64
    },
    "51": {
        "unshifted": 34,
        "shifted": 51,
        "alted": 35
    },
    "52": {
        "unshifted": 39,
        "shifted": 52,
        "alted": 123
    },
    "53": {
        "unshifted": 40,
        "shifted": 53,
        "alted": 91
    },
    "54": {
        "unshifted": 167,
        "shifted": 54,
        "alted": 94
    },
    "55": {
        "unshifted": 232,
        "shifted": 55
    },
    "56": {
        "unshifted": 33,
        "shifted": 56
    },
    "57": {
        "unshifted": 231,
        "shifted": 57,
        "alted": 123
    },
    "69": {
        "alted": 8364
    },
    "186": {
        "unshifted": 36,
        "shifted": 42,
        "alted": 93
    },
    "187": {
        "unshifted": 61,
        "shifted": 43,
        "alted": 126
    },
    "188": {
        "unshifted": 44,
        "shifted": 63
    },
    "189": {
        "unshifted": 45,
        "shifted": 95
    },
    "190": {
        "unshifted": 59,
        "shifted": 46
    },
    "191": {
        "unshifted": 58,
        "shifted": 47
    },
    "192": {
        "unshifted": 249,
        "shifted": 37,
        "alted": 180
    },
    "219": {
        "unshifted": 41,
        "shifted": 176
    },
    "220": {
        "unshifted": 181,
        "shifted": 163,
        "alted": 96
    },
    "221": {
        "unshifted": 94,
        "shifted": 168,
        "alted": 91
    },
    "222": {
        "unshifted": 178,
        "shifted": 179
    },
    "226": {
        "unshifted": 60,
        "shifted": 62,
        "alted": 92
    }
}
```

**Comment by filoozom** [comment]
That one actually works pretty well.
I only noticed an issue with the accent characters, which print without waiting for an additional character:
- ¨a gives ¨ä
- ¨n gives ¨¨n
- ^a gives ^â
- ^n gives ^^n
- ...

But this doesn't have anything to do with the keymap, it'll need a change to the JavaScript to handle accents.

**Comment by andischerer** [comment]
checkout v1.1.7 fr_BE layout is merged and accent-keys should work as expected.

**Pull request merged**
